

"""
Constantes du domaine des communications Easy Projet.
"""

COMMUNICATION_CONVERSATION_TITLE_LENGTH = 200

COMMUNICATION_SENDER_NAME_LENGTH = 200
COMMUNICATION_EMAIL_LENGTH = 254

COMMUNICATION_ATTACHMENT_FILENAME_LENGTH = 255
COMMUNICATION_ATTACHMENT_MIME_TYPE_LENGTH = 255

COMMUNICATION_ERROR_DETAILS_LENGTH = 2000

COMMUNICATION_SUBJECT_LENGTH = 200