

"""
Constantes de l'entité Company.
"""

from .common import (
    ADDRESS_LENGTH,
    CITY_LENGTH,
    COUNTRY_LENGTH,
    EMAIL_LENGTH,
    PHONE_LENGTH,
    POSTAL_CODE_LENGTH,
)

COMPANY_NAME_LENGTH = 150

COMPANY_SIRET_LENGTH = 14
COMPANY_VAT_NUMBER_LENGTH = 32

COMPANY_EMAIL_LENGTH = EMAIL_LENGTH
COMPANY_PHONE_LENGTH = PHONE_LENGTH

COMPANY_ADDRESS_LENGTH = ADDRESS_LENGTH

COMPANY_POSTAL_CODE_LENGTH = POSTAL_CODE_LENGTH
COMPANY_CITY_LENGTH = CITY_LENGTH
COMPANY_COUNTRY_LENGTH = COUNTRY_LENGTH