

SIGNATURE_EMAIL_LENGTH = 254
SIGNATURE_EVENT_TYPE_LENGTH = 64
SIGNATURE_FILENAME_LENGTH = 255
SIGNATURE_NAME_LENGTH = 255
SIGNATURE_PROVIDER_IDENTIFIER_LENGTH = 255
SIGNATURE_REQUEST_TITLE_LENGTH = 255