

"""
Constantes de l'entité User.
"""

from .common import (
    EMAIL_LENGTH,
    PHONE_LENGTH,
)

USER_LAST_NAME_LENGTH = 100
USER_FIRST_NAME_LENGTH = 100
USER_PREFERRED_NAME_LENGTH = 100
USER_INITIALS_LENGTH = 10

USER_EMAIL_LENGTH = EMAIL_LENGTH
USER_PHONE_LENGTH = PHONE_LENGTH
USER_MOBILE_LENGTH = PHONE_LENGTH

USER_LANGUAGE_LENGTH = 10
USER_TIMEZONE_LENGTH = 50
USER_THEME_LENGTH = 20