

"""
Constantes de l'entité WorkPackage.
"""

from .common import (
    CODE_LENGTH,
    NAME_LENGTH,
)

WORK_PACKAGE_CODE_LENGTH = CODE_LENGTH
WORK_PACKAGE_NAME_LENGTH = NAME_LENGTH

WORK_PACKAGE_DESCRIPTION_LENGTH = 2000

WORK_PACKAGE_DEFAULT_WORKLOAD_HOURS = 0