# Generated by Django 6.0.7 on 2026-08-04 09:24

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0003_alter_catalogvalue_options_and_more'),
        ('companies', '0004_company_siret_company_vat_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence')),
                ('name', models.CharField(max_length=150, verbose_name='Nom du projet')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Projet actif')),
                ('contract_reference', models.CharField(blank=True, max_length=100, verbose_name='Référence contractuelle')),
                ('comments', models.TextField(blank=True, max_length=4000, verbose_name='Commentaires')),
                ('address_1', models.CharField(blank=True, max_length=150, verbose_name='Adresse')),
                ('address_2', models.CharField(blank=True, max_length=150, verbose_name="Complément d'adresse")),
                ('address_3', models.CharField(blank=True, max_length=150, verbose_name="Complément d'adresse 2")),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Code postal')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Pays')),
                ('planned_workload_hours', models.PositiveIntegerField(default=0, verbose_name='Charge prévisionnelle (h)')),
                ('contractual_start_date', models.DateField(blank=True, null=True, verbose_name='Date contractuelle de début')),
                ('contractual_end_date', models.DateField(blank=True, null=True, verbose_name='Date contractuelle de fin')),
                ('start_date_review', models.DateField(blank=True, null=True, verbose_name='Date révisée de début')),
                ('end_date_review', models.DateField(blank=True, null=True, verbose_name='Date révisée de fin')),
                ('receipt_date_init', models.DateField(blank=True, null=True, verbose_name='Date initiale de réception')),
                ('receipt_date_review', models.DateField(blank=True, null=True, verbose_name='Date révisée de réception')),
                ('delivery_date_init', models.DateField(blank=True, null=True, verbose_name='Date initiale de livraison')),
                ('delivery_date_review', models.DateField(blank=True, null=True, verbose_name='Date révisée de livraison')),
                ('amount_quote_ht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant du devis HT')),
                ('amount_quote_ttc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant du devis TTC')),
                ('amount_order_ht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant de la commande HT')),
                ('amount_order_ttc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant de la commande TTC')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Devise')),
                ('budget_comments', models.TextField(blank=True, max_length=4000, verbose_name='Commentaires budgétaires')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_projects', to='companies.company', verbose_name='Société responsable')),
                ('designer_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='designed_projects', to='companies.company', verbose_name="Maître d'œuvre")),
                ('owner_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_projects', to='companies.company', verbose_name="Maître d'ouvrage")),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Chef de projet')),
                ('project_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='type_projects', to='catalogs.catalogvalue', verbose_name='Type de projet')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_projects', to='catalogs.catalogvalue', verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'db_table': 'project',
                'ordering': ['reference', 'name'],
            },
        ),
    ]
