# Generated by Django 6.0.7 on 2026-08-11 17:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_alter_catalogvalue_options_and_more'),
        ('core', '0001_initial'),
        ('projects', '0002_project_client_environment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client_environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='core.clientenvironment', verbose_name='Environnement client'),
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='projects.project', verbose_name='Projet')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_memberships', to='catalogs.catalogvalue', verbose_name='Rôle sur le projet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Affectation au projet',
                'verbose_name_plural': 'Affectations aux projets',
                'db_table': 'project_membership',
                'ordering': ['project', 'user__last_name', 'user__first_name'],
                'constraints': [models.UniqueConstraint(fields=('project', 'user'), name='uq_project_membership_project_user')],
            },
        ),
    ]
