# Generated by Django 6.0.7 on 2026-08-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_client_environment_projectmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, editable=False, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='project',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, editable=False, max_digits=9, null=True, verbose_name='Longitude'),
        ),
    ]
