# Generated by Django 6.0.7 on 2026-08-14 07:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_alter_catalogvalue_options_and_more'),
        ('projects', '0004_project_latitude_project_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectExternalParticipant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse électronique')),
                ('company_name', models.CharField(blank=True, max_length=150, verbose_name='Société')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('access_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_external_participants', to='catalogs.catalogvalue', verbose_name="Niveau d'accès")),
                ('converted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_external_participations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur créé')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_participants', to='projects.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Intervenant externe au projet',
                'verbose_name_plural': 'Intervenants externes aux projets',
                'db_table': 'project_external_participant',
                'ordering': ['project', 'last_name', 'first_name'],
                'constraints': [models.UniqueConstraint(fields=('project', 'email'), name='uq_project_external_participant_project_email')],
            },
        ),
    ]
