# Generated by Django 6.0.7 on 2026-08-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectexternalparticipant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contractual_end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='contractual_start_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='delivery_date_init',
        ),
        migrations.RemoveField(
            model_name='project',
            name='delivery_date_review',
        ),
        migrations.RemoveField(
            model_name='project',
            name='end_date_review',
        ),
        migrations.RemoveField(
            model_name='project',
            name='receipt_date_init',
        ),
        migrations.RemoveField(
            model_name='project',
            name='receipt_date_review',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date_review',
        ),
        migrations.AddField(
            model_name='project',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Livraison'),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fin'),
        ),
        migrations.AddField(
            model_name='project',
            name='initial_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Livraison initiale'),
        ),
        migrations.AddField(
            model_name='project',
            name='initial_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fin initiale'),
        ),
        migrations.AddField(
            model_name='project',
            name='initial_receipt_date',
            field=models.DateField(blank=True, null=True, verbose_name='Réception initiale'),
        ),
        migrations.AddField(
            model_name='project',
            name='initial_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Début initial'),
        ),
        migrations.AddField(
            model_name='project',
            name='receipt_date',
            field=models.DateField(blank=True, null=True, verbose_name='Réception'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Début'),
        ),
    ]
