# Generated by Django 6.0.7 on 2026-08-25 10:01

import apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_project_contractual_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.projects.models.project_photo_upload_to, verbose_name='Photo du projet'),
        ),
    ]
