# Generated by Django 6.0.7 on 2026-09-06 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_alter_catalogvalue_options_and_more'),
        ('projects', '0007_project_project_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmembership',
            name='access_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_access_memberships', to='catalogs.catalogvalue', verbose_name="Niveau d'accès au projet"),
        ),
    ]
