# Generated by Django 6.0.7 on 2026-09-06 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_alter_catalogvalue_options_and_more'),
        ('projects', '0008_projectmembership_access_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembership',
            name='access_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_access_memberships', to='catalogs.catalogvalue', verbose_name="Niveau d'accès au projet"),
        ),
    ]
