# Generated by Django 6.0.7 on 2026-09-06 16:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_logo'),
        ('projects', '0009_alter_projectmembership_access_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCompany',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_participations', to='companies.company', verbose_name='Société')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_companies', to='projects.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Société participante au projet',
                'verbose_name_plural': 'Sociétés participantes aux projets',
                'db_table': 'project_company',
                'ordering': ['project', 'company__name'],
                'constraints': [models.UniqueConstraint(fields=('project', 'company'), name='uq_project_company_project_company')],
            },
        ),
    ]
