# Generated by Django 6.0.7 on 2026-09-06 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_alter_catalogvalue_options_and_more'),
        ('projects', '0010_projectcompany'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmembership',
            name='is_project_manager_responsible',
            field=models.BooleanField(default=False, verbose_name='Chef de projet titulaire'),
        ),
        migrations.AddConstraint(
            model_name='projectmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_project_manager_responsible', True)), fields=('project',), name='uq_project_membership_active_responsible'),
        ),
    ]
