# Generated by Django 6.0.7 on 2026-09-07 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_projectmembership_is_project_manager_responsible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_manager',
        ),
    ]
