# Generated by Django 6.0.7 on 2026-10-10 11:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_project_project_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='progress_percent',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Avancement (%)'),
        ),
    ]
