# Generated by Django 6.0.7 on 2026-08-05 14:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0003_alter_catalogvalue_options_and_more'),
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('code', models.CharField(max_length=30, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='Description')),
                ('planned_start_date', models.DateField(blank=True, null=True, verbose_name='Début planifié')),
                ('planned_end_date', models.DateField(blank=True, null=True, verbose_name='Fin planifiée')),
                ('updated_start_date', models.DateField(blank=True, null=True, verbose_name='Début révisé')),
                ('updated_end_date', models.DateField(blank=True, null=True, verbose_name='Fin révisée')),
                ('planned_workload_hours', models.PositiveIntegerField(default=0, verbose_name='Charge planifiée (h)')),
                ('remaining_workload_hours', models.PositiveIntegerField(default=0, verbose_name='Reste à faire (h)')),
                ('progress_percent', models.PositiveSmallIntegerField(default=0, verbose_name='Avancement (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Tâche active')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_statuses', to='catalogs.catalogvalue', verbose_name='Statut')),
                ('work_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='work.workpackage', verbose_name='Lot de travaux')),
            ],
            options={
                'verbose_name': 'Tâche',
                'verbose_name_plural': 'Tâches',
                'db_table': 'task',
                'ordering': ['work_package', 'code', 'name'],
                'constraints': [models.UniqueConstraint(fields=('work_package', 'code'), name='uniq_task_code_by_work_package')],
            },
        ),
    ]
