# Generated by Django 6.0.7 on 2026-08-15 07:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_alter_catalogvalue_options_and_more'),
        ('tasks', '0002_alter_task_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('is_active', models.BooleanField(default=True, verbose_name='Affectation active')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_assignment_roles', to='catalogs.catalogvalue', verbose_name='Rôle sur la tâche')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tasks.task', verbose_name='Tâche')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Affectation à une tâche',
                'verbose_name_plural': 'Affectations aux tâches',
                'db_table': 'task_assignment',
                'ordering': ['task', 'user__last_name', 'user__first_name'],
                'constraints': [models.UniqueConstraint(fields=('task', 'user'), name='uniq_task_assignment_user')],
            },
        ),
    ]
