# Generated by Django 6.0.7 on 2026-08-19

from django.db import migrations, models


def migrate_task_dates(apps, schema_editor):
    """
    Recopie les anciennes dates de planification vers
    la nouvelle nomenclature avant suppression des champs historiques.

    - planned_* devient initial_*
    - updated_* devient la date courante
    - si updated_* est vide, la date courante reprend planned_*
    """

    Task = apps.get_model(
        "tasks",
        "Task",
    )

    for task in Task.objects.all():
        task.initial_start_date = (
            task.planned_start_date
        )

        task.initial_end_date = (
            task.planned_end_date
        )

        task.start_date = (
            task.updated_start_date
            or task.planned_start_date
        )

        task.end_date = (
            task.updated_end_date
            or task.planned_end_date
        )

        task.save(
            update_fields=[
                "initial_start_date",
                "initial_end_date",
                "start_date",
                "end_date",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        (
            "tasks",
            "0003_taskassignment",
        ),
    ]

    operations = [
        # --------------------------------------------------------------
        # Création des nouveaux champs
        # --------------------------------------------------------------

        migrations.AddField(
            model_name="task",
            name="end_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fin",
            ),
        ),

        migrations.AddField(
            model_name="task",
            name="initial_end_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fin initiale",
            ),
        ),

        migrations.AddField(
            model_name="task",
            name="initial_start_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Début initial",
            ),
        ),

        migrations.AddField(
            model_name="task",
            name="start_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Début",
            ),
        ),

        # --------------------------------------------------------------
        # Migration des données
        # --------------------------------------------------------------

        migrations.RunPython(
            migrate_task_dates,
            migrations.RunPython.noop,
        ),

        # --------------------------------------------------------------
        # Suppression des anciens champs
        # --------------------------------------------------------------

        migrations.RemoveField(
            model_name="task",
            name="planned_end_date",
        ),

        migrations.RemoveField(
            model_name="task",
            name="planned_start_date",
        ),

        migrations.RemoveField(
            model_name="task",
            name="updated_end_date",
        ),

        migrations.RemoveField(
            model_name="task",
            name="updated_start_date",
        ),
    ]