# Generated by Django 6.0.7 on 2026-08-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_planned_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='allocation_percent',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Taux de charge (%)'),
        ),
    ]
