# Generated by Django 6.0.7 on 2026-08-20 12:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_taskassignment_allocation_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('dependency_type', models.CharField(choices=[('FS', 'Fin → Début'), ('SS', 'Début → Début'), ('FF', 'Fin → Fin'), ('SF', 'Début → Fin')], default='FS', max_length=2, verbose_name='Type de dépendance')),
                ('lag_days', models.IntegerField(default=0, verbose_name='Décalage (jours)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Dépendance active')),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successor_dependencies', to='tasks.task', verbose_name='Tâche antécédente')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessor_dependencies', to='tasks.task', verbose_name='Tâche successeure')),
            ],
            options={
                'verbose_name': 'Dépendance de tâche',
                'verbose_name_plural': 'Dépendances de tâches',
                'db_table': 'task_dependency',
                'ordering': ['predecessor__work_package', 'predecessor__code', 'successor__code'],
                'constraints': [models.UniqueConstraint(fields=('predecessor', 'successor'), name='uniq_task_dependency_predecessor_successor'), models.CheckConstraint(condition=models.Q(('predecessor', models.F('successor')), _negated=True), name='task_dependency_predecessor_not_successor')],
            },
        ),
    ]
