# Generated by Django 6.0.7 on 2026-09-23

from decimal import Decimal

from django.db import migrations, models


def preserve_existing_task_corrections(
    apps,
    schema_editor,
):
    task_model = apps.get_model("tasks", "Task")

    task_model.objects.exclude(
        remaining_workload_hours=models.F(
            "planned_workload_hours"
        ),
    ).update(
        remaining_workload_hours_is_manual=True,
    )

    task_model.objects.exclude(
        progress_percent=0,
    ).update(
        progress_percent_is_manual=True,
    )


def restore_existing_tasks_to_automatic_mode(
    apps,
    schema_editor,
):
    task_model = apps.get_model("tasks", "Task")

    task_model.objects.update(
        remaining_workload_hours_is_manual=False,
        progress_percent_is_manual=False,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_taskdependency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="remaining_workload_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=8,
                verbose_name="Reste à faire (h)",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="progress_percent_is_manual",
            field=models.BooleanField(
                default=False,
                verbose_name="Avancement corrigé manuellement",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="remaining_workload_hours_is_manual",
            field=models.BooleanField(
                default=False,
                verbose_name="Reste à faire corrigé manuellement",
            ),
        ),
        migrations.RunPython(
            preserve_existing_task_corrections,
            restore_existing_tasks_to_automatic_mode,
        ),
    ]
