# Generated by Django 6.0.7 on 2026-10-08 16:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_alter_catalogvalue_options_and_more'),
        ('tasks', '0007_task_workload_automation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fin réelle'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Début réel'),
        ),
        migrations.CreateModel(
            name='TaskJobRequirement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('planned_workload_hours', models.PositiveIntegerField(verbose_name='Heures prévues')),
                ('is_active', models.BooleanField(default=True, verbose_name='Besoin actif')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_job_requirements', to='catalogs.catalogvalue', verbose_name='Métier')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requirements', to='tasks.task', verbose_name='Tâche')),
            ],
            options={
                'verbose_name': "Besoin métier d'une tâche",
                'verbose_name_plural': "Besoins métiers d'une tâche",
                'db_table': 'task_job_requirement',
                'ordering': ['task', 'job__sort_order', 'job__label'],
                'constraints': [models.UniqueConstraint(fields=('task', 'job'), name='uniq_task_job_requirement')],
            },
        ),
    ]
