# Generated by Django 6.0.7 on 2026-08-17 07:32

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0003_alter_catalogvalue_options_and_more'),
        ('tasks', '0003_taskassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('period_start_date', models.DateField(verbose_name='Début de période')),
                ('period_end_date', models.DateField(verbose_name='Fin de période')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Transmis le')),
                ('global_comment', models.CharField(blank=True, max_length=250, verbose_name='Commentaire')),
                ('is_active', models.BooleanField(default=True, verbose_name='Rapport actif')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_report_statuses', to='catalogs.catalogvalue', verbose_name='Statut')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_reports', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Rapport d'activité",
                'verbose_name_plural': "Rapports d'activité",
                'db_table': 'activity_report',
                'ordering': ['-period_start_date', 'user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityReportLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('comment', models.CharField(blank=True, max_length=250, verbose_name='Commentaire')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ligne active')),
                ('activity_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='reporting.activityreport', verbose_name="Rapport d'activité")),
                ('line_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_report_lines', to='catalogs.catalogvalue', verbose_name="Type d'activité")),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_report_lines', to='tasks.task', verbose_name='Tâche')),
            ],
            options={
                'verbose_name': "Ligne de rapport d'activité",
                'verbose_name_plural': "Lignes de rapport d'activité",
                'db_table': 'activity_report_line',
                'ordering': ['activity_report', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityReportEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('activity_date', models.DateField(verbose_name='Date')),
                ('regular_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Heures normales')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Heures supplémentaires')),
                ('activity_report_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='reporting.activityreportline', verbose_name='Ligne de rapport')),
            ],
            options={
                'verbose_name': "Saisie journalière du rapport d'activité",
                'verbose_name_plural': "Saisies journalières des rapports d'activité",
                'db_table': 'activity_report_entry',
                'ordering': ['activity_report_line', 'activity_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='activityreport',
            constraint=models.UniqueConstraint(fields=('user', 'period_start_date'), name='uniq_activity_report_user_week'),
        ),
        migrations.AddConstraint(
            model_name='activityreportline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('line_type__isnull', True), ('task__isnull', False)), models.Q(('line_type__isnull', False), ('task__isnull', True)), _connector='OR'), name='chk_activity_report_line_source'),
        ),
        migrations.AddConstraint(
            model_name='activityreportline',
            constraint=models.UniqueConstraint(condition=models.Q(('task__isnull', False)), fields=('activity_report', 'task'), name='uniq_activity_report_task'),
        ),
        migrations.AddConstraint(
            model_name='activityreportline',
            constraint=models.UniqueConstraint(condition=models.Q(('line_type__isnull', False)), fields=('activity_report', 'line_type'), name='uniq_activity_report_line_type'),
        ),
        migrations.AddConstraint(
            model_name='activityreportentry',
            constraint=models.UniqueConstraint(fields=('activity_report_line', 'activity_date'), name='uniq_activity_report_entry_day'),
        ),
        migrations.AddConstraint(
            model_name='activityreportentry',
            constraint=models.CheckConstraint(condition=models.Q(('regular_hours__gte', 0)), name='chk_activity_report_regular_hours'),
        ),
        migrations.AddConstraint(
            model_name='activityreportentry',
            constraint=models.CheckConstraint(condition=models.Q(('overtime_hours__gte', 0)), name='chk_activity_report_overtime_hours'),
        ),
    ]
