# Generated by Django 6.0.7 on 2026-08-18 07:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectexternalparticipant'),
        ('reporting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityReportProjectReview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('status', models.CharField(choices=[('PENDING', 'À valider'), ('VALIDATED', 'Validé')], default='PENDING', max_length=20, verbose_name='État')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Validé le')),
                ('activity_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_reviews', to='reporting.activityreport', verbose_name="Rapport d'activité")),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_report_reviews', to='projects.project', verbose_name='Projet')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_report_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': "Validation de rapport d'activité par projet",
                'verbose_name_plural': "Validations de rapports d'activité par projet",
                'db_table': 'activity_report_project_review',
                'ordering': ['-activity_report__period_start_date', 'project__reference', 'activity_report__user__last_name', 'activity_report__user__first_name'],
                'constraints': [models.UniqueConstraint(fields=('activity_report', 'project'), name='uniq_activity_report_project_review')],
            },
        ),
    ]
