# Generated by Django 6.0.7 on 2026-08-18 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_activityreportprojectreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityreportprojectreview',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='activityreportprojectreview',
            name='uniq_activity_report_project_review',
        ),
        migrations.AlterModelTable(
            name='activityreportprojectreview',
            table=None,
        ),
    ]
