# Generated by Django 6.0.7 on 2026-09-06 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_project_photo'),
        ('reporting', '0003_alter_activityreportprojectreview_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityreportprojectreview',
            options={'ordering': ['-activity_report__period_start_date', 'project__reference', 'activity_report__user__last_name', 'activity_report__user__first_name'], 'permissions': [('review_activity_reports', "Peut consulter et valider les rapports d'activité")], 'verbose_name': "Validation de rapport d'activité par projet", 'verbose_name_plural': "Validations de rapports d'activité par projet"},
        ),
        migrations.AddConstraint(
            model_name='activityreportprojectreview',
            constraint=models.UniqueConstraint(fields=('activity_report', 'project'), name='uniq_activity_report_project_review'),
        ),
        migrations.AlterModelTable(
            name='activityreportprojectreview',
            table='activity_report_project_review',
        ),
    ]
