# Generated by Django 6.0.7 on 2026-09-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reporting",
            "0004_alter_activityreportprojectreview_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityreportprojectreview",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "À valider"),
                    ("VALIDATED", "Validé"),
                    ("IGNORED", "Ignoré"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="État",
            ),
        ),
    ]
