# Generated by Django 6.0.7 on 2026-07-10 16:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=150, verbose_name='Nom usuel')),
                ('legal_name', models.CharField(max_length=150, verbose_name='Raison sociale')),
                ('email', models.EmailField(max_length=100, verbose_name='Adresse électronique')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('address_1', models.CharField(blank=True, max_length=100, verbose_name='Adresse')),
                ('address_2', models.CharField(blank=True, max_length=100, verbose_name="Complément d'adresse")),
                ('address_3', models.CharField(blank=True, max_length=100, verbose_name="Complément d'adresse 2")),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='Ville')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='Pays')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Société',
                'verbose_name_plural': 'Sociétés',
                'db_table': 'company',
                'ordering': ['name'],
            },
        ),
    ]
