# Generated by Django 6.0.7 on 2026-07-21 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='code',
        ),
        migrations.RemoveField(
            model_name='company',
            name='legal_name',
        ),
    ]
