# Generated by Django 6.0.7 on 2026-07-25 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_remove_company_code_remove_company_legal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='siret',
            field=models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator(message='Le SIRET doit contenir exactement 14 chiffres.', regex='^\\d{14}$')], verbose_name='SIRET'),
        ),
        migrations.AddField(
            model_name='company',
            name='vat_number',
            field=models.CharField(blank=True, max_length=32, verbose_name='Numéro de TVA intracommunautaire'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_1',
            field=models.CharField(blank=True, max_length=150, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_2',
            field=models.CharField(blank=True, max_length=150, verbose_name="Complément d'adresse"),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_3',
            field=models.CharField(blank=True, max_length=150, verbose_name="Complément d'adresse 2"),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Adresse électronique'),
        ),
        migrations.AlterField(
            model_name='company',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Code postal'),
        ),
    ]
