# Generated by Django 6.0.7 on 2026-08-09 09:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0003_alter_catalogvalue_options_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalIntegration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('code', models.CharField(max_length=30, verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('priority', models.PositiveIntegerField(default=100, help_text="Plus la valeur est faible, plus l'intégration est prioritaire.", validators=[django.core.validators.MinValueValidator(1)], verbose_name='Priorité')),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Paramètres techniques non sensibles du connecteur.', verbose_name='Configuration')),
                ('credential_reference', models.CharField(blank=True, help_text='Référence vers un stockage sécurisé de credentials. Aucun secret ne doit être stocké directement ici.', max_length=255, verbose_name='Référence des credentials')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('client_environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_integrations', to='core.clientenvironment', verbose_name='Environnement client')),
                ('connection_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integration_connection_statuses', to='catalogs.catalogvalue', verbose_name='État de connexion')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integration_providers', to='catalogs.catalogvalue', verbose_name='Fournisseur')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integration_service_types', to='catalogs.catalogvalue', verbose_name='Type de service')),
            ],
            options={
                'verbose_name': 'Intégration externe',
                'verbose_name_plural': 'Intégrations externes',
                'db_table': 'external_integration',
                'ordering': ['client_environment', 'service_type', 'priority', 'name'],
                'constraints': [models.UniqueConstraint(fields=('client_environment', 'code'), name='uniq_external_integration_code_by_client_environment')],
            },
        ),
    ]
