# Generated by Django 6.0.7 on 2026-08-02 10:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0003_alter_catalogvalue_options_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('reference', models.CharField(help_text='Numéro de commande client ou numéro de devis.', max_length=100, verbose_name='Référence commerciale')),
                ('project_capacity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacité en projets')),
                ('purchase_date', models.DateField(verbose_name="Date d'attribution")),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('client_environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='core.clientenvironment', verbose_name='Environnement client')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='catalogs.catalogvalue', verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Licence',
                'verbose_name_plural': 'Licences',
                'db_table': 'license',
                'ordering': ['-purchase_date', 'reference'],
                'constraints': [models.UniqueConstraint(fields=('client_environment', 'reference'), name='uniq_license_reference_by_environment')],
            },
        ),
    ]
