# Generated by Django 6.0.7 on 2026-08-02 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='license',
            options={'ordering': ['-granted_at', 'reference'], 'verbose_name': 'Licence', 'verbose_name_plural': 'Licences'},
        ),
        migrations.RenameField(
            model_name='license',
            old_name='purchase_date',
            new_name='granted_at',
        ),
    ]
