# Generated by Django 6.0.7 on 2026-08-26 17:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('projects', '0007_project_project_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('origin', models.CharField(choices=[('PERSONAL', 'Personnelle'), ('ASSIGNED', 'Assignée')], default='PERSONAL', max_length=20, verbose_name='Origine')),
                ('title', models.CharField(max_length=150, verbose_name='Titre')),
                ('details', models.TextField(blank=True, verbose_name='Détails')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('status', models.CharField(choices=[('TODO', 'À faire'), ('IN_PROGRESS', 'En cours'), ('SUSPENDED', 'Suspendue'), ('COMPLETED', 'Terminée'), ('ABANDONED', 'Abandonnée')], default='TODO', max_length=20, verbose_name='État')),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date de réalisation')),
                ('context_object_id', models.UUIDField(blank=True, null=True, verbose_name='Objet associé')),
                ('context_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype', verbose_name="Type d'objet associé")),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_todo_actions', to=settings.AUTH_USER_MODEL, verbose_name='Rédacteur')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo_actions', to='projects.project', verbose_name='Projet associé')),
            ],
            options={
                'verbose_name': 'Action Todo',
                'verbose_name_plural': 'Actions Todo',
                'db_table': 'todo_action',
                'ordering': ['status', 'due_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TodoActionRecipient',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('role', models.CharField(choices=[('ACTION', 'Pour action'), ('INFORMATION', 'Pour information'), ('COLLABORATION', 'Action commune')], max_length=20, verbose_name='Rôle')),
                ('read_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date de lecture')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='todos.todoaction', verbose_name='Action')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='todo_actions_received', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'db_table': 'todo_action_recipient',
                'ordering': ['action', 'user__last_name', 'user__first_name'],
                'constraints': [models.UniqueConstraint(fields=('action', 'user'), name='uniq_todo_action_recipient')],
            },
        ),
    ]
