# Generated by Django 6.0.7 on 2026-08-31 16:52

import apps.communications.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_documentfavorite_and_more'),
        ('projects', '0007_project_project_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationConversation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Sujet')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_communication_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_conversations', to='projects.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'db_table': 'communication_conversation',
                'ordering': ['project', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('origin', models.CharField(choices=[('INTERNAL', 'Easy Projet'), ('IMPORTED_EMAIL', 'Email importé'), ('MOBILE', 'Application mobile'), ('SYSTEM', 'Système')], default='INTERNAL', max_length=20, verbose_name='Origine')),
                ('sender_name', models.CharField(blank=True, max_length=200, verbose_name="Nom de l'expéditeur")),
                ('sender_email', models.EmailField(blank=True, max_length=254, verbose_name="Adresse de l'expéditeur")),
                ('body', models.TextField(blank=True, verbose_name='Message')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='communication_messages', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communications.communicationconversation', verbose_name='Conversation')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imported_communication_messages', to=settings.AUTH_USER_MODEL, verbose_name='Importé par')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'communication_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationMessageAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to=apps.communications.models.communication_attachment_upload_to, verbose_name='Fichier')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Nom du fichier')),
                ('mime_type', models.CharField(blank=True, max_length=255, verbose_name='Type MIME')),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Taille du fichier')),
                ('document_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='communication_attachments', to='documents.documentversion', verbose_name='Version documentaire')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='communications.communicationmessage', verbose_name='Message')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communication_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Déposé par')),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
                'db_table': 'communication_message_attachment',
                'ordering': ['message', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationMessageRecipient',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('destination_email', models.EmailField(blank=True, max_length=254, verbose_name='Adresse de destination')),
                ('channel', models.CharField(choices=[('INTERNAL', 'Messagerie interne'), ('EMAIL', 'Email'), ('MOBILE', 'Application mobile')], max_length=20, verbose_name='Canal')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Envoyé'), ('DELIVERED', 'Distribué'), ('READ', 'Lu'), ('FAILED', 'Échec')], default='PENDING', max_length=20, verbose_name='État')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Distribué le')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lu le')),
                ('error_details', models.TextField(blank=True, max_length=2000, verbose_name="Détail de l'erreur")),
                ('external_participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='communication_messages', to='projects.projectexternalparticipant', verbose_name='Intervenant externe')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='communications.communicationmessage', verbose_name='Message')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_communication_messages', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Destinataire',
                'verbose_name_plural': 'Destinataires',
                'db_table': 'communication_message_recipient',
                'ordering': ['message', 'created_at'],
            },
        ),
    ]
