# Generated by Django 6.0.7 on 2026-09-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=200, verbose_name='Objet'),
        ),
        migrations.AddField(
            model_name='communicationmessagerecipient',
            name='purpose',
            field=models.CharField(choices=[('ACTION', 'Pour action'), ('INFORMATION', 'Pour information')], default='INFORMATION', max_length=20, verbose_name='Type de diffusion'),
        ),
    ]
