# Generated by Django 6.0.7 on 2026-09-27 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_communicationconversation_projects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communicationmessageattachment',
            options={'ordering': ['message', 'created_at'], 'verbose_name': 'Pièce jointe de communication', 'verbose_name_plural': 'Pièces jointes de communication'},
        ),
    ]
