# Generated by Django 6.0.7 on 2026-07-09 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=100, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_hierarchical', models.BooleanField(default=False, verbose_name='Hiérarchique')),
                ('is_editable', models.BooleanField(default=False, verbose_name='Modifiable')),
                ('is_incremental', models.BooleanField(default=False, verbose_name='Incrémental')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Type de catalogue',
                'verbose_name_plural': 'Types de catalogues',
                'db_table': 'catalog_type',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='CatalogValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('code', models.CharField(max_length=30, verbose_name='Code')),
                ('label', models.CharField(max_length=100, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('level', models.PositiveIntegerField(default=0, verbose_name='Niveau')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_system', models.BooleanField(default=False, verbose_name='Système')),
                ('is_default', models.BooleanField(default=False, verbose_name='Valeur par défaut')),
                ('catalog_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='catalogs.catalogtype', verbose_name='Type de catalogue')),
            ],
            options={
                'verbose_name': 'Valeur de catalogue',
                'verbose_name_plural': 'Valeurs de catalogue',
                'db_table': 'catalog_value',
                'ordering': ['catalog_type', 'sort_order', 'label'],
                'constraints': [models.UniqueConstraint(fields=('catalog_type', 'code'), name='uniq_catalog_value_type_code'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('catalog_type',), name='uniq_default_value_by_catalog_type')],
            },
        ),
    ]
