# Generated by Django 6.0.7 on 2026-07-22 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogtype',
            name='is_hierarchical',
        ),
        migrations.RemoveField(
            model_name='catalogvalue',
            name='level',
        ),
    ]
