# Generated by Django 6.0.7 on 2026-07-22 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_remove_catalogtype_is_hierarchical_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogvalue',
            options={'ordering': ['catalog_type', 'level', 'sort_order', 'label'], 'verbose_name': 'Valeur de catalogue', 'verbose_name_plural': 'Valeurs de catalogue'},
        ),
        migrations.AddField(
            model_name='catalogtype',
            name='is_hierarchical',
            field=models.BooleanField(default=False, verbose_name='Hiérarchique'),
        ),
        migrations.AddField(
            model_name='catalogvalue',
            name='level',
            field=models.PositiveIntegerField(default=0, verbose_name='Niveau'),
        ),
        migrations.AddField(
            model_name='catalogvalue',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalogs.catalogvalue', verbose_name='Valeur parente'),
        ),
    ]
