# Generated by Django 6.0.7 on 2026-08-02 10:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_company_siret_company_vat_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientEnvironment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='client_environment', to='companies.company', verbose_name='Société cliente')),
            ],
            options={
                'verbose_name': 'Environnement client',
                'verbose_name_plural': 'Environnements clients',
                'db_table': 'client_environment',
                'ordering': ['company__name'],
            },
        ),
    ]
