# Generated by Django 6.0.7 on 2026-09-06 12:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_alter_catalogvalue_options_and_more'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientEnvironmentMembership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('is_client_admin', models.BooleanField(default=False, verbose_name='Administrateur client')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('client_environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_memberships', to='core.clientenvironment', verbose_name='Environnement client')),
                ('employment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_environment_memberships', to='catalogs.catalogvalue', verbose_name="Type d'emploi")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_environment_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Rattachement utilisateur à un environnement client',
                'verbose_name_plural': 'Rattachements utilisateurs aux environnements clients',
                'db_table': 'client_environment_membership',
                'ordering': ['client_environment', 'user__last_name', 'user__first_name'],
                'constraints': [models.UniqueConstraint(fields=('client_environment', 'user'), name='uq_client_environment_membership_environment_user')],
            },
        ),
    ]
