# Generated by Django 6.0.7 on 2026-09-06 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_alter_catalogvalue_options_and_more'),
        ('core', '0002_clientenvironmentmembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientenvironmentmembership',
            name='is_client_admin_responsible',
            field=models.BooleanField(default=False, verbose_name='Administrateur client titulaire'),
        ),
        migrations.AddConstraint(
            model_name='clientenvironmentmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_client_admin_responsible', True)), fields=('client_environment',), name='uq_client_environment_membership_active_responsible'),
        ),
    ]
