

from framework.form import (
    FieldDefinition,
    FormDefinition,
    SectionDefinition,
)
from framework.types.field_width import FieldWidth


RISK_FORM_DEFINITION = FormDefinition(
    name="risk",
    title="Risque",
    sections=[
        SectionDefinition(
            title="Rattachement",
            fields=[
                FieldDefinition(
                    name="project",
                    width=FieldWidth.SM,
                ),
                FieldDefinition(
                    name="owner",
                    width=FieldWidth.SM,
                ),
            ],
        ),
        SectionDefinition(
            title="Classification",
            fields=[
                FieldDefinition(
                    name="origin",
                    width=FieldWidth.SM,
                ),
                FieldDefinition(
                    name="risk_type",
                    width=FieldWidth.SM,
                ),
                FieldDefinition(
                    name="risk_class",
                    width=FieldWidth.SM,
                ),
                FieldDefinition(
                    name="impact",
                    width=FieldWidth.SM,
                ),
                FieldDefinition(
                    name="severity",
                    width=FieldWidth.SM,
                ),
                FieldDefinition(
                    name="probability",
                    width=FieldWidth.SM,
                ),
                FieldDefinition(
                    name="status",
                    width=FieldWidth.SM,
                ),
                FieldDefinition(
                    name="criticality",
                    width=FieldWidth.SM,
                ),
                FieldDefinition(
                    name="review_frequency",
                    width=FieldWidth.SM,
                ),
            ],
        ),
        SectionDefinition(
            title="Identification",
            fields=[
                FieldDefinition(
                    name="reference",
                    width=FieldWidth.SM,
                ),
                FieldDefinition(
                    name="title",
                    width=FieldWidth.FULL,
                ),
                FieldDefinition(
                    name="description",
                    width=FieldWidth.FULL,
                ),
                FieldDefinition(
                    name="is_active",
                    required=False,
                    width=FieldWidth.FULL,
                    checked_label="Actif",
                    unchecked_label="Inactif",
                ),
            ],
        ),
        SectionDefinition(
            title="Évaluation",
            fields=[
                FieldDefinition(
                    name="occurrence_date",
                    width=FieldWidth.SM,
                ),
                FieldDefinition(
                    name="closure_date",
                    width=FieldWidth.SM,
                ),
                FieldDefinition(
                    name="estimated_cost",
                    width=FieldWidth.SM,
                ),
                FieldDefinition(
                    name="last_review_date",
                    width=FieldWidth.SM,
                ),
                FieldDefinition(
                    name="planned_actions",
                    width=FieldWidth.FULL,
                ),
            ],
        ),
    ],
)