# Generated by Django 6.0.7 on 2026-09-27 12:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_clientenvironmentmembership_is_client_admin_responsible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFolderTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='Description')),
                ('is_default', models.BooleanField(default=False, verbose_name='Arborescence par défaut')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('client_environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_folder_templates', to='core.clientenvironment', verbose_name='Environnement client')),
            ],
            options={
                'verbose_name': "Modèle d'arborescence documentaire",
                'verbose_name_plural': "Modèles d'arborescences documentaires",
                'db_table': 'document_folder_template',
                'ordering': ['client_environment__company__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentFolderTemplateFolder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='client_configuration.documentfoldertemplatefolder', verbose_name='Dossier parent')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='client_configuration.documentfoldertemplate', verbose_name="Modèle d'arborescence")),
            ],
            options={
                'verbose_name': "Dossier de modèle d'arborescence",
                'verbose_name_plural': "Dossiers de modèles d'arborescences",
                'db_table': 'document_folder_template_folder',
                'ordering': ['template', 'parent__sort_order', 'parent__name', 'sort_order', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='documentfoldertemplate',
            constraint=models.UniqueConstraint(fields=('client_environment', 'name'), name='uq_doc_folder_tpl_env_name'),
        ),
        migrations.AddConstraint(
            model_name='documentfoldertemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default', True)), fields=('client_environment',), name='uq_doc_folder_tpl_env_default'),
        ),
        migrations.AddConstraint(
            model_name='documentfoldertemplatefolder',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('template', 'name'), name='uq_doc_folder_tpl_root_name'),
        ),
        migrations.AddConstraint(
            model_name='documentfoldertemplatefolder',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('template', 'parent', 'name'), name='uq_doc_folder_tpl_child_name'),
        ),
    ]
