# Generated by Django 6.0.7 on 2026-08-06 12:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0003_alter_catalogvalue_options_and_more'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('reference', models.CharField(blank=True, max_length=30, verbose_name='Référence')),
                ('title', models.CharField(max_length=150, verbose_name='Titre')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='Description')),
                ('occurrence_date', models.DateField(blank=True, null=True, verbose_name="Date d'apparition")),
                ('closure_date', models.DateField(blank=True, null=True, verbose_name='Date de clôture')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Coût estimé')),
                ('last_review_date', models.DateField(blank=True, null=True, verbose_name='Date de la dernière revue')),
                ('planned_actions', models.TextField(blank=True, max_length=2000, verbose_name='Actions prévues')),
                ('is_active', models.BooleanField(default=True, verbose_name='Risque actif')),
                ('criticality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_criticalities', to='catalogs.catalogvalue', verbose_name='Criticité')),
                ('impact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_impacts', to='catalogs.catalogvalue', verbose_name='Impact')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_origins', to='catalogs.catalogvalue', verbose_name='Origine')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_risks', to=settings.AUTH_USER_MODEL, verbose_name='Pilote')),
                ('probability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_probabilities', to='catalogs.catalogvalue', verbose_name='Probabilité')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risks', to='projects.project', verbose_name='Projet')),
                ('review_frequency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_review_frequencies', to='catalogs.catalogvalue', verbose_name='Fréquence de revue')),
                ('risk_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_classes', to='catalogs.catalogvalue', verbose_name='Classe')),
                ('risk_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_types', to='catalogs.catalogvalue', verbose_name='Type')),
                ('severity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_severities', to='catalogs.catalogvalue', verbose_name='Gravité')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_statuses', to='catalogs.catalogvalue', verbose_name='État')),
            ],
            options={
                'verbose_name': 'Risque',
                'verbose_name_plural': 'Risques',
                'db_table': 'risk',
                'ordering': ['project', 'reference', 'title'],
                'constraints': [models.UniqueConstraint(fields=('project', 'reference'), name='uniq_risk_reference_by_project')],
            },
        ),
    ]
