# Generated by Django 6.0.7 on 2026-08-21 08:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0003_alter_catalogvalue_options_and_more'),
        ('projects', '0006_remove_project_contractual_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFolder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Dossier actif')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.documentfolder', verbose_name='Dossier parent')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_folders', to='projects.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Dossier documentaire',
                'verbose_name_plural': 'Dossiers documentaires',
                'db_table': 'document_folder',
                'ordering': ['project', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('is_doe', models.BooleanField(default=False, verbose_name='Sélectionné pour le DOE')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_documents', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_type_documents', to='catalogs.catalogvalue', verbose_name='Type de document')),
                ('lifecycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_lifecycle_documents', to='catalogs.catalogvalue', verbose_name='État GED')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project', verbose_name='Projet')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_status_documents', to='catalogs.catalogvalue', verbose_name='Statut métier')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documentfolder', verbose_name='Dossier')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'document',
                'ordering': ['project', 'folder', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('version_number', models.PositiveIntegerField(editable=False, verbose_name='Version')),
                ('original_filename', models.CharField(max_length=255, verbose_name="Nom du fichier d'origine")),
                ('storage_key', models.CharField(editable=False, max_length=500, unique=True, verbose_name='Clé de stockage')),
                ('mime_type', models.CharField(blank=True, max_length=150, verbose_name='Type MIME')),
                ('file_size', models.PositiveBigIntegerField(verbose_name='Taille du fichier')),
                ('checksum', models.CharField(editable=False, max_length=64, verbose_name='Empreinte SHA-256')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_document_versions', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Version de document',
                'verbose_name_plural': 'Versions de documents',
                'db_table': 'document_version',
                'ordering': ['document', 'version_number'],
            },
        ),
        migrations.CreateModel(
            name='DocumentHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('action', models.CharField(choices=[('CREATED', 'Création'), ('IMPORTED', 'Import'), ('OPENED', 'Ouverture'), ('VERSION_CREATED', 'Nouvelle version'), ('RENAMED', 'Renommage'), ('MOVED', 'Déplacement'), ('COPIED', 'Copie'), ('DOWNLOADED', 'Téléchargement'), ('SHARED', 'Partage'), ('ARCHIVED', 'Archivage'), ('RESTORED', 'Restauration'), ('TRASHED', 'Mise en corbeille'), ('SIGNED', 'Signature'), ('DOE_SELECTED', 'Sélection DOE'), ('DOE_UNSELECTED', 'Retrait DOE')], max_length=40, verbose_name='Action')),
                ('details', models.TextField(blank=True, max_length=2000, verbose_name='Détails')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='documents.document', verbose_name='Document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_history_entries', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='documents.documentversion', verbose_name='Version')),
            ],
            options={
                'verbose_name': 'Historique documentaire',
                'verbose_name_plural': 'Historique documentaire',
                'db_table': 'document_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='documents.documentversion', verbose_name='Version courante'),
        ),
        migrations.AddConstraint(
            model_name='documentfolder',
            constraint=models.UniqueConstraint(fields=('project', 'parent', 'name'), name='uniq_document_folder_name_by_parent', nulls_distinct=False,),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version_number'), name='uniq_document_version_number'),
        ),
    ]
