# Generated by Django 6.0.7 on 2026-08-23 11:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('projects', '0006_remove_project_contractual_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFavorite',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
            ],
            options={
                'verbose_name': 'Document favori',
                'verbose_name_plural': 'Documents favoris',
                'db_table': 'document_favorite',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='documentfolder',
            name='uniq_document_folder_name_by_parent',
        ),
        migrations.AddConstraint(
            model_name='documentfolder',
            constraint=models.UniqueConstraint(fields=('project', 'parent', 'name'), name='uniq_document_folder_name_by_parent'),
        ),
        migrations.AddField(
            model_name='documentfavorite',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='documents.document', verbose_name='Document'),
        ),
        migrations.AddField(
            model_name='documentfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_favorites', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddConstraint(
            model_name='documentfavorite',
            constraint=models.UniqueConstraint(fields=('user', 'document'), name='uniq_document_favorite_user_document'),
        ),
    ]
