# Generated by Django 6.0.7 on 2026-09-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentfavorite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='extension',
            field=models.CharField(blank=True, editable=False, max_length=20, verbose_name='Extension'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='technical_type',
            field=models.CharField(blank=True, choices=[('CAD', 'CAO'), ('OFFICE', 'Bureautique'), ('PDF', 'PDF'), ('IMAGE', 'Image'), ('MEDIA', 'Audio / vidéo'), ('OTHER', 'Autre')], editable=False, max_length=20, verbose_name='Type technique'),
        ),
    ]
