# Generated by Django 6.0.7 on 2026-09-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_populate_document_technical_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentversion',
            name='extension',
            field=models.CharField(editable=False, max_length=20, verbose_name='Extension'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='technical_type',
            field=models.CharField(choices=[('CAD', 'CAO'), ('OFFICE', 'Bureautique'), ('PDF', 'PDF'), ('IMAGE', 'Image'), ('MEDIA', 'Audio / vidéo'), ('OTHER', 'Autre')], editable=False, max_length=20, verbose_name='Type technique'),
        ),
    ]
