# Generated by Django 6.0.7 on 2026-09-03 16:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_documentversion_extension_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentEditLock',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('expires_at', models.DateTimeField(verbose_name='Expiration')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='edit_lock', to='documents.document', verbose_name='Document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_edit_locks', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_locks', to='documents.documentversion', verbose_name='Version')),
            ],
            options={
                'verbose_name': "Verrou d'édition documentaire",
                'verbose_name_plural': "Verrous d'édition documentaire",
                'db_table': 'document_edit_lock',
                'ordering': ['expires_at'],
            },
        ),
    ]
