# Generated by Django 6.0.7 on 2026-09-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_documenteditlock'),
        ('projects', '0007_project_project_photo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documentfolder',
            name='uniq_document_folder_name_by_parent',
        ),
        migrations.AddConstraint(
            model_name='documentfolder',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('project', 'parent', 'name'), name='uniq_document_folder_name_by_parent'),
        ),
        migrations.AddConstraint(
            model_name='documentfolder',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('project', 'name'), name='uniq_document_root_folder_name_by_project'),
        ),
    ]
