# Generated by Django 6.0.7 on 2026-10-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_remove_documentfolder_uniq_document_folder_name_by_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Commentaire'),
        ),
    ]
