# Generated by Django 6.0.7 on 2026-10-03 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_alter_catalogvalue_options_and_more'),
        ('documents', '0008_document_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_type_documents', to='catalogs.catalogvalue', verbose_name='Type de document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_status_documents', to='catalogs.catalogvalue', verbose_name='Statut métier'),
        ),
    ]
