# Generated by Django 6.0.7 on 2026-10-03 15:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_alter_document_document_type_alter_document_status'),
        ('projects', '0012_remove_project_project_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doe_source_document',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doe_copies', to='documents.document', verbose_name='Document source du DOE'),
        ),
        migrations.AddField(
            model_name='document',
            name='is_doe_generated',
            field=models.BooleanField(default=False, editable=False, verbose_name='Généré pour le DOE'),
        ),
        migrations.AddField(
            model_name='documentfolder',
            name='is_doe',
            field=models.BooleanField(default=False, verbose_name='Sélectionné pour le DOE'),
        ),
        migrations.AddField(
            model_name='documentfolder',
            name='is_doe_generated',
            field=models.BooleanField(default=False, editable=False, verbose_name='Dossier généré par le DOE'),
        ),
        migrations.AddField(
            model_name='documentfolder',
            name='is_doe_root',
            field=models.BooleanField(default=False, editable=False, verbose_name='Racine DOE'),
        ),
        migrations.CreateModel(
            name='DoeGeneration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('document_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de documents')),
                ('doe_root_folder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doe_generations', to='documents.documentfolder', verbose_name='Dossier DOE')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_does', to=settings.AUTH_USER_MODEL, verbose_name='Généré par')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doe_generations', to='projects.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Génération de DOE',
                'verbose_name_plural': 'Générations de DOE',
                'db_table': 'doe_generation',
                'ordering': ['-created_at'],
            },
        ),
    ]
