# Generated by Django 6.0.7 on 2026-10-04 11:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_document_doe_source_document_and_more'),
        ('integrations', '0001_initial'),
        ('projects', '0012_remove_project_project_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('title', models.CharField(max_length=255, verbose_name='Intitulé')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SENT', 'Envoyée'), ('PARTIALLY_SIGNED', 'Partiellement signée'), ('COMPLETED', 'Signée'), ('REFUSED', 'Refusée'), ('CANCELLED', 'Annulée'), ('EXPIRED', 'Expirée'), ('FAILED', 'En erreur')], default='DRAFT', max_length=32, verbose_name='État')),
                ('provider_request_id', models.CharField(blank=True, max_length=255, verbose_name='Identifiant de demande prestataire')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyée le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminée le')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expire le')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_signature_requests', to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
                ('external_integration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signature_requests', to='integrations.externalintegration', verbose_name='Intégration de signature')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_requests', to='projects.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Demande de signature',
                'verbose_name_plural': 'Demandes de signature',
                'db_table': 'signature_request',
                'ordering': ['-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SignatureRequestDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('READY', 'Prêt à envoyer'), ('SENT', 'Envoyé'), ('SIGNED', 'Signé'), ('REFUSED', 'Refusé'), ('FAILED', 'En erreur')], default='DRAFT', max_length=16, verbose_name='État')),
                ('provider_document_id', models.CharField(blank=True, max_length=255, verbose_name='Identifiant de document prestataire')),
                ('prepared_storage_key', models.CharField(blank=True, editable=False, max_length=500, verbose_name='Clé du PDF préparé')),
                ('prepared_filename', models.CharField(blank=True, editable=False, max_length=255, verbose_name='Nom du PDF préparé')),
                ('prepared_mime_type', models.CharField(blank=True, editable=False, max_length=150, verbose_name='Type MIME du PDF préparé')),
                ('prepared_file_size', models.PositiveBigIntegerField(blank=True, editable=False, null=True, verbose_name='Taille du PDF préparé')),
                ('prepared_checksum', models.CharField(blank=True, editable=False, max_length=64, verbose_name='Empreinte du PDF préparé')),
                ('prepared_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Préparé le')),
                ('signed_storage_key', models.CharField(blank=True, editable=False, max_length=500, verbose_name='Clé du PDF signé')),
                ('signed_filename', models.CharField(blank=True, editable=False, max_length=255, verbose_name='Nom du PDF signé')),
                ('signed_mime_type', models.CharField(blank=True, editable=False, max_length=150, verbose_name='Type MIME du PDF signé')),
                ('signed_file_size', models.PositiveBigIntegerField(blank=True, editable=False, null=True, verbose_name='Taille du PDF signé')),
                ('signed_checksum', models.CharField(blank=True, editable=False, max_length=64, verbose_name='Empreinte du PDF signé')),
                ('signed_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Signé le')),
                ('signature_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.signaturerequest', verbose_name='Demande de signature')),
                ('source_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signature_request_documents', to='documents.documentversion', verbose_name='Version source')),
            ],
            options={
                'verbose_name': 'Document à signer',
                'verbose_name_plural': 'Documents à signer',
                'db_table': 'signature_request_document',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignatureRequestRecipient',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nom du signataire')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail du signataire')),
                ('signing_order', models.PositiveIntegerField(default=1, help_text='Les signataires du même ordre peuvent signer en parallèle.', verbose_name='Ordre de signature')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Invitation envoyée'), ('VIEWED', 'Consulté'), ('SIGNED', 'Signé'), ('REFUSED', 'Refusé'), ('EXPIRED', 'Expiré'), ('FAILED', 'En erreur')], default='PENDING', max_length=16, verbose_name='État')),
                ('provider_recipient_id', models.CharField(blank=True, max_length=255, verbose_name='Identifiant de signataire prestataire')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Signé le')),
                ('signature_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='documents.signaturerequest', verbose_name='Demande de signature')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature_request_recipients', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur interne')),
            ],
            options={
                'verbose_name': 'Signataire',
                'verbose_name_plural': 'Signataires',
                'db_table': 'signature_request_recipient',
                'ordering': ['signing_order', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='SignatureEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('event_type', models.CharField(max_length=64, verbose_name="Type d'événement")),
                ('provider_event_id', models.CharField(blank=True, max_length=255, verbose_name="Identifiant d'événement prestataire")),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name="Données de l'événement")),
                ('signature_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='documents.signaturerequest', verbose_name='Demande de signature')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='documents.signaturerequestrecipient', verbose_name='Signataire')),
            ],
            options={
                'verbose_name': 'Événement de signature',
                'verbose_name_plural': 'Événements de signature',
                'db_table': 'signature_event',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='signaturerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_request_id', ''), _negated=True), fields=('external_integration', 'provider_request_id'), name='uniq_signature_request_provider_identifier'),
        ),
        migrations.AddConstraint(
            model_name='signaturerequestdocument',
            constraint=models.UniqueConstraint(fields=('signature_request', 'source_version'), name='uniq_signature_request_source_version'),
        ),
        migrations.AddConstraint(
            model_name='signaturerequestrecipient',
            constraint=models.UniqueConstraint(fields=('signature_request', 'email'), name='uniq_signature_request_recipient_email'),
        ),
        migrations.AddConstraint(
            model_name='signatureevent',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_event_id', ''), _negated=True), fields=('signature_request', 'provider_event_id'), name='uniq_signature_event_provider_identifier'),
        ),
    ]
