# Generated by Django 6.0.7 on 2026-07-26 07:55

import apps.users.models.managers
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalogs', '0003_alter_catalogvalue_options_and_more'),
        ('companies', '0004_company_siret_company_vat_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('preferred_name', models.CharField(blank=True, max_length=100, verbose_name="Prénom d'usage")),
                ('initials', models.CharField(editable=False, max_length=10, verbose_name='Initiales')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/photos/', verbose_name='Photo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse électronique')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='Téléphone mobile')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('language', models.CharField(blank=True, max_length=10, verbose_name='Langue')),
                ('timezone', models.CharField(blank=True, max_length=50, verbose_name='Fuseau horaire')),
                ('theme', models.CharField(blank=True, max_length=20, verbose_name='Thème')),
                ('access_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_level_users', to='catalogs.catalogvalue', verbose_name="Niveau d'accès")),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='companies.company', verbose_name='Société')),
                ('employment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employment_type_users', to='catalogs.catalogvalue', verbose_name="Type d'emploi")),
                ('global_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='global_role_users', to='catalogs.catalogvalue', verbose_name='Rôle global')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_users', to='catalogs.catalogvalue', verbose_name='Métier')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'user',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', apps.users.models.managers.UserManager()),
            ],
        ),
    ]
