# Generated by Django 6.0.7 on 2026-08-01 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='language',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='timezone',
        ),
    ]
