# Generated by Django 6.0.7 on 2026-08-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_language_remove_user_preferred_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name="Accès à l'administration"),
        ),
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('system', 'Système'), ('light', 'Clair'), ('dark', 'Sombre')], default='system', max_length=20, verbose_name='Thème'),
        ),
    ]
