# Generated by Django 6.0.7 on 2026-09-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_staff_alter_user_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='Changement de mot de passe obligatoire'),
        ),
        migrations.AddField(
            model_name='user',
            name='temporary_password_sent_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Mot de passe provisoire envoyé le'),
        ),
    ]
