# Generated by Django 6.0.7 on 2026-09-06 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_must_change_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='employment_type',
        ),
    ]
