# Generated by Django 6.0.7 on 2026-09-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_system_admin',
            field=models.BooleanField(default=False, verbose_name='Administrateur système'),
        ),
    ]
