# Generated by Django 6.0.7 on 2026-09-06 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_access_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='global_role',
        ),
    ]
