# Generated by Django 6.0.7 on 2026-09-30 18:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_global_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserListPreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('list_identifier', models.CharField(max_length=100, verbose_name='Identifiant de liste')),
                ('visible_column_identifiers', models.JSONField(default=list, verbose_name='Colonnes visibles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Préférence de liste utilisateur',
                'verbose_name_plural': 'Préférences de listes utilisateur',
                'db_table': 'user_list_preference',
                'ordering': ['user', 'list_identifier'],
                'constraints': [models.UniqueConstraint(fields=('user', 'list_identifier'), name='uq_user_list_pref_user_list')],
            },
        ),
    ]
