

from framework.form import (
    FieldDefinition,
    FormCollectionColumnDefinition,
    FormCollectionDefinition,
    FormDefinition,
    SectionDefinition,
)
from framework.types.field_width import FieldWidth


PROJECT_FORM_DEFINITION = FormDefinition(
    name="project",
    title="Projet",
    sections=[
        SectionDefinition(
            title="Identification",
            fields=[
                FieldDefinition(
                    name="reference",
                    width=FieldWidth.XS,
                ),
                FieldDefinition(
                    name="name",
                    width=FieldWidth.MD,
                ),
                FieldDefinition(
                    name="description",
                    width=FieldWidth.FULL,
                ),
                FieldDefinition(
                    name="company",
                    width=FieldWidth.XS,
                ),
                FieldDefinition(
                    name="status",
                    width=FieldWidth.XS,
                ),
                FieldDefinition(
                    name="is_active",
                    required=False,
                    width=FieldWidth.XS,
                    checked_label="Actif",
                    unchecked_label="Inactif",
                ),
            ],
        ),
        SectionDefinition(
            title="Client et contrat",
            fields=[
                FieldDefinition(
                    name="owner_company",
                    width=FieldWidth.XS,
                ),
                FieldDefinition(
                    name="designer_company",
                    width=FieldWidth.XS,
                ),
                FieldDefinition(
                    name="project_type",
                    width=FieldWidth.XS,
                ),
                FieldDefinition(
                    name="contract_reference",
                    width=FieldWidth.XS,
                ),
                FieldDefinition(
                    name="comments",
                    width=FieldWidth.FULL,
                ),
            ],
        ),
        SectionDefinition(
            title="Localisation",
            fields=[
                FieldDefinition(
                    name="address_1",
                    width=FieldWidth.MD,
                ),
                FieldDefinition(
                    name="address_2",
                    width=FieldWidth.XS,
                ),
                FieldDefinition(
                    name="address_3",
                    width=FieldWidth.XS,
                ),
                FieldDefinition(
                    name="postal_code",
                    width=FieldWidth.XS,
                ),
                FieldDefinition(
                    name="city",
                    width=FieldWidth.MD,
                ),
                FieldDefinition(
                    name="country",
                    width=FieldWidth.XS,
                ),
            ],
        ),
        SectionDefinition(
            title="Planning et charge",
            fields=[
                FieldDefinition(
                    name="initial_start_date",
                    width=FieldWidth.XS,
                ),
                FieldDefinition(
                    name="initial_end_date",
                    width=FieldWidth.XS,
                ),
                FieldDefinition(
                    name="start_date",
                    width=FieldWidth.XS,
                ),
                FieldDefinition(
                    name="end_date",
                    width=FieldWidth.XS,
                ),
                FieldDefinition(
                    name="initial_receipt_date",
                    width=FieldWidth.XS,
                ),
                FieldDefinition(
                    name="receipt_date",
                    width=FieldWidth.XS,
                ),
                FieldDefinition(
                    name="initial_delivery_date",
                    width=FieldWidth.XS,
                ),
                FieldDefinition(
                    name="delivery_date",
                    width=FieldWidth.XS,
                ),
                FieldDefinition(
                    name="planned_workload_hours",
                    width=FieldWidth.XS,
                ),
            ],
        ),
        SectionDefinition(
            title="Données commerciales",
            fields=[
                FieldDefinition(
                    name="amount_quote_ht",
                    width=FieldWidth.XS,
                ),
                FieldDefinition(
                    name="amount_quote_ttc",
                    width=FieldWidth.XS,
                ),
                FieldDefinition(
                    name="amount_order_ht",
                    width=FieldWidth.XS,
                ),
                FieldDefinition(
                    name="amount_order_ttc",
                    width=FieldWidth.XS,
                ),
                FieldDefinition(
                    name="currency",
                    width=FieldWidth.XS,
                ),
                FieldDefinition(
                    name="budget_comments",
                    width=FieldWidth.FULL,
                ),
            ],
        ),
    ],
    collections=[
        FormCollectionDefinition(
            name="memberships",
            title="Participants internes",
            description=(
                "Utilisateurs Easy Projet affectés au projet."
            ),
            columns=(
                FormCollectionColumnDefinition(
                    name="user",
                    label="Utilisateur",
                    field_name="user",
                ),
                FormCollectionColumnDefinition(
                    name="role",
                    label="Rôle sur le projet",
                    field_name="role",
                ),
                FormCollectionColumnDefinition(
                    name="access_level",
                    label="Niveau d'accès",
                    field_name="access_level",
                ),
                FormCollectionColumnDefinition(
                    name="is_project_manager_responsible",
                    label="Titulaire",
                    field_name="is_project_manager_responsible",
                ),
                FormCollectionColumnDefinition(
                    name="is_active",
                    label="Actif",
                    field_name="is_active",
                ),
            ),
            allow_add=True,
            allow_delete=True,
            add_label="Ajouter un participant",
            delete_label="Supprimer le participant",
        ),
        FormCollectionDefinition(
            name="external_participants",
            title="Participants externes",
            description=(
                "Intervenants ponctuels ne disposant pas "
                "nécessairement d'un compte Easy Projet."
            ),
            columns=(
                FormCollectionColumnDefinition(
                    name="last_name",
                    label="Nom",
                    field_name="last_name",
                ),
                FormCollectionColumnDefinition(
                    name="first_name",
                    label="Prénom",
                    field_name="first_name",
                ),
                FormCollectionColumnDefinition(
                    name="email",
                    label="Adresse électronique",
                    field_name="email",
                ),
                FormCollectionColumnDefinition(
                    name="company_name",
                    label="Société",
                    field_name="company_name",
                ),
                FormCollectionColumnDefinition(
                    name="access_level",
                    label="Niveau d'accès",
                    field_name="access_level",
                ),
                FormCollectionColumnDefinition(
                    name="is_active",
                    label="Actif",
                    field_name="is_active",
                ),
            ),
            allow_add=True,
            allow_delete=True,
            add_label="Ajouter un participant externe",
            delete_label="Supprimer le participant externe",
        ),
    ],
)