

from framework.form import (
    FieldDefinition,
    FormDefinition,
    SectionDefinition,
)
from framework.types.field_width import FieldWidth


PROJECT_FORM_DEFINITION = FormDefinition(
    name="project",
    title="Projet",
    sections=[
        SectionDefinition(
            title="Identification",
            fields=[
                FieldDefinition(
                    name="reference",
                ),
                FieldDefinition(
                    name="name",
                ),
                FieldDefinition(
                    name="description",
                    width=FieldWidth.FULL,
                ),
                FieldDefinition(
                    name="company",
                ),
                FieldDefinition(
                    name="project_manager",
                ),
                FieldDefinition(
                    name="status",
                ),
                FieldDefinition(
                    name="is_active",
                    required=False,
                    width=FieldWidth.FULL,
                    checked_label="Actif",
                    unchecked_label="Inactif",
                ),
            ],
        ),
        SectionDefinition(
            title="Client et contrat",
            fields=[
                FieldDefinition(
                    name="owner_company",
                ),
                FieldDefinition(
                    name="designer_company",
                ),
                FieldDefinition(
                    name="project_type",
                ),
                FieldDefinition(
                    name="contract_reference",
                ),
                FieldDefinition(
                    name="comments",
                    width=FieldWidth.FULL,
                ),
            ],
        ),
        SectionDefinition(
            title="Localisation",
            fields=[
                FieldDefinition(
                    name="address_1",
                    width=FieldWidth.FULL,
                ),
                FieldDefinition(
                    name="address_2",
                    width=FieldWidth.FULL,
                ),
                FieldDefinition(
                    name="address_3",
                    width=FieldWidth.FULL,
                ),
                FieldDefinition(
                    name="postal_code",
                ),
                FieldDefinition(
                    name="city",
                ),
                FieldDefinition(
                    name="country",
                ),
            ],
        ),
        SectionDefinition(
            title="Charge et planning",
            fields=[
                FieldDefinition(
                    name="planned_workload_hours",
                ),
                FieldDefinition(
                    name="initial_start_date",
                ),
                FieldDefinition(
                    name="initial_end_date",
                ),
                FieldDefinition(
                    name="start_date",
                ),
                FieldDefinition(
                    name="end_date",
                ),
                FieldDefinition(
                    name="initial_receipt_date",
                ),
                FieldDefinition(
                    name="receipt_date",
                ),
                FieldDefinition(
                    name="initial_delivery_date",
                ),
                FieldDefinition(
                    name="delivery_date",
                ),
            ],
        ),
        SectionDefinition(
            title="Données commerciales",
            fields=[
                FieldDefinition(
                    name="amount_quote_ht",
                ),
                FieldDefinition(
                    name="amount_quote_ttc",
                ),
                FieldDefinition(
                    name="amount_order_ht",
                ),
                FieldDefinition(
                    name="amount_order_ttc",
                ),
                FieldDefinition(
                    name="currency",
                ),
                FieldDefinition(
                    name="budget_comments",
                    width=FieldWidth.FULL,
                ),
            ],
        ),
    ],
)