"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from .env import load_local_environment

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_local_environment(BASE_DIR)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(b-+7x1@5z_7-h1j57_)qo001bc(=da@20!)6h8t_45bw12@$1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    ".trycloudflare.com",
    "host.docker.internal",
]


# Application definition

INSTALLED_APPS = [
    # Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Easy Projet
    "apps.core",
    "apps.catalogs",
    "apps.companies",
    "apps.licenses",
    "apps.projects",
    "apps.work",
    "apps.reporting",
    "apps.documents",
    "apps.finance",
    "apps.meetings",
    "apps.users",
    "apps.tasks",
    "apps.risks",
    "apps.integrations.apps.IntegrationsConfig",
    "apps.planning.apps.PlanningConfig",
    "apps.todos",
    "apps.communications.apps.CommunicationsConfig",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    "apps.core.middleware.dev_auto_login.DevelopmentAutoLoginMiddleware",
    "apps.core.middleware.password_change_required.PasswordChangeRequiredMiddleware",
    "apps.core.middleware.active_company.ActiveCompanyMiddleware",

    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "apps.todos.context_processors.todo_context",
                "apps.projects.context_processors.current_project",
            ],
            "libraries": {
                "ep_form_fields": (
                    "framework.integrations.django."
                    "templatetags.ep_form_fields"
                ),
                "ep_forms": "common.templatetags.ep_forms",
                "ep_lists": "common.templatetags.ep_lists",
                "ep_buttons": "common.templatetags.ep_buttons",
            },
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

AUTH_USER_MODEL = "users.User"

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "easy_projet",
        "USER": "easy_projet_user",
        "PASSWORD": "EasyProjet",
        "HOST": "localhost",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

#***********************************
# Stockage documents - test
#***********************************
DOCUMENT_STORAGE_ROOT = (
    BASE_DIR
    / "var"
    / "documents"
)
# ----------------------------------------------------------------------
# Verrouillage documentaire (156 minutes)
# ----------------------------------------------------------------------

DOCUMENT_EDIT_LOCK_TIMEOUT_SECONDS = int(
    os.getenv(
        "DOCUMENT_EDIT_LOCK_TIMEOUT_SECONDS",
        "900",
    )
)

# ***********************************
# Médias applicatifs
# ***********************************

MEDIA_URL = "/media/"

MEDIA_ROOT = (
    BASE_DIR
    / "var"
    / "media"
)

#***********************************
# Authentification
#***********************************
DEV_AUTO_LOGIN = (
    DEBUG
    and os.environ.get("EASY_PROJET_DEV_AUTO_LOGIN") == "1"
)

DEV_AUTO_LOGIN_EMAIL = os.environ.get(
    "EASY_PROJET_DEV_AUTO_LOGIN_EMAIL",
    "",
)

LOGIN_URL = "users:login"
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "users:login"

# ***********************************
# Google Maps
# ***********************************

GOOGLE_MAPS_API_KEY = os.environ.get(
    "EASY_PROJET_GOOGLE_MAPS_API_KEY",
    "",
)

# ***********************************
# OnlyOffice
# ***********************************
ONLYOFFICE_URL = os.environ.get(
    "ONLYOFFICE_URL",
    default="",
)

EASY_PROJET_PUBLIC_URL = os.environ.get(
    "EASY_PROJET_PUBLIC_URL",
    "",
)

ONLYOFFICE_JWT_SECRET = os.environ.get(
    "ONLYOFFICE_JWT_SECRET",
    default="",
)


# ***********************************
# Email
# ***********************************

EMAIL_BACKEND = (
    "django.core.mail.backends.smtp.EmailBackend"
)

EMAIL_HOST = os.getenv(
    "EMAIL_HOST",
    "",
)

EMAIL_PORT = int(
    os.getenv(
        "EMAIL_PORT",
        "465",
    )
)

EMAIL_HOST_USER = os.getenv(
    "EMAIL_HOST_USER",
    "",
)

EMAIL_HOST_PASSWORD = os.getenv(
    "EMAIL_HOST_PASSWORD",
    "",
)

EMAIL_USE_SSL = (
    os.getenv(
        "EMAIL_USE_SSL",
        "false",
    ).lower()
    == "true"
)

EMAIL_USE_TLS = (
    os.getenv(
        "EMAIL_USE_TLS",
        "false",
    ).lower()
    == "true"
)

DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL",
    EMAIL_HOST_USER,
)


# ***********************************
# CADViewer
# ***********************************
CADVIEWER_FRONTEND_URL = os.getenv(
    "CADVIEWER_FRONTEND_URL",
    "",
)

CADVIEWER_BACKEND_URL = os.getenv(
    "CADVIEWER_BACKEND_URL",
    "",
)

CADVIEWER_CVKEY = os.getenv(
    "CADVIEWER_CVKEY",
    "",
)