

# framework/defaults/column.py

DEFAULT_COLUMN_VISIBLE = True
DEFAULT_COLUMN_SORTABLE = True
DEFAULT_COLUMN_WIDTH = "auto"
DEFAULT_COLUMN_TRUNCATE = True
DEFAULT_COLUMN_ORDER = 0
DEFAULT_COLUMN_ALIGN = "left"