

from framework.types.field_width import FieldWidth

# framework/defaults/field.py

DEFAULT_FIELD_LABEL = None
DEFAULT_FIELD_KIND = "text"
DEFAULT_FIELD_REQUIRED = False
DEFAULT_FIELD_READONLY = False
DEFAULT_FIELD_VISIBLE = True
DEFAULT_FIELD_PLACEHOLDER = None
DEFAULT_FIELD_HELP_TEXT = None
DEFAULT_FIELD_WIDTH = FieldWidth.AUTO
DEFAULT_FIELD_AUTOFOCUS = False
DEFAULT_FIELD_AUTOCOMPLETE = None
DEFAULT_FIELD_TAB_INDEX = None
DEFAULT_FIELD_ICON = None