# Generated by Django 6.0.7 on 2026-08-06 16:33

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0003_alter_catalogvalue_options_and_more'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('reference', models.CharField(blank=True, max_length=30, verbose_name='Référence')),
                ('subject', models.CharField(max_length=150, verbose_name='Objet')),
                ('scheduled_at', models.DateTimeField(verbose_name='Date et heure')),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('999.99'))], verbose_name='Durée (h)')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Lieu')),
                ('notes', models.TextField(blank=True, help_text="Informations transmises aux participants avec l'invitation.", max_length=2000, verbose_name='Notes de convocation')),
                ('comments', models.TextField(blank=True, help_text='Informations internes non transmises aux participants.', max_length=2000, verbose_name='Commentaires internes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Réunion active')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organized_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Organisateur')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to='projects.project', verbose_name='Projet')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meeting_statuses', to='catalogs.catalogvalue', verbose_name='État')),
            ],
            options={
                'verbose_name': 'Réunion',
                'verbose_name_plural': 'Réunions',
                'db_table': 'meeting',
                'ordering': ['project', '-scheduled_at', 'reference'],
            },
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('external_name', models.CharField(blank=True, max_length=150, verbose_name='Nom du participant externe')),
                ('external_email', models.EmailField(blank=True, max_length=254, verbose_name='Email du participant externe')),
                ('is_active', models.BooleanField(default=True, verbose_name='Participation active')),
                ('invitation_response', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meeting_invitation_responses', to='catalogs.catalogvalue', verbose_name="Réponse à l'invitation")),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='meetings.meeting', verbose_name='Réunion')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meeting_participations', to=settings.AUTH_USER_MODEL, verbose_name='Participant interne')),
            ],
            options={
                'verbose_name': 'Participant à une réunion',
                'verbose_name_plural': 'Participants aux réunions',
                'db_table': 'meeting_participant',
                'ordering': ['meeting', 'participant', 'external_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.UniqueConstraint(fields=('project', 'reference'), name='uniq_meeting_reference_by_project'),
        ),
        migrations.AddConstraint(
            model_name='meetingparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('participant__isnull', False)), fields=('meeting', 'participant'), name='uniq_internal_participant_by_meeting'),
        ),
    ]
