# Generated by Django 6.0.7 on 2026-08-06 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_alter_catalogvalue_options_and_more'),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingparticipant',
            name='invitation_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meeting_invitation_responses', to='catalogs.catalogvalue', verbose_name="Réponse à l'invitation"),
        ),
    ]
