# Generated by Django 6.0.7 on 2026-08-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_alter_meetingparticipant_invitation_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='agenda',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Ordre du jour'),
        ),
    ]
