# Generated by Django 6.0.7 on 2026-09-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0003_meeting_agenda"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="invitations_sent_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Invitations envoyées le",
            ),
        ),
    ]
