# Generated by Django 6.0.7 on 2026-08-04 18:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0003_alter_catalogvalue_options_and_more'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPackage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('code', models.CharField(max_length=30, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='Description')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fin')),
                ('planned_workload_hours', models.PositiveIntegerField(default=0, verbose_name='Charge planifiée (h)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Lot actif')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_work_packages', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_packages', to='projects.project', verbose_name='Projet')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_package_statuses', to='catalogs.catalogvalue', verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Lot de travaux',
                'verbose_name_plural': 'Lots de travaux',
                'db_table': 'work_package',
                'ordering': ['project', 'code', 'name'],
                'constraints': [models.UniqueConstraint(fields=('project', 'code'), name='uniq_work_package_code_by_project')],
            },
        ),
    ]
