# Generated by Django 6.0.7 on 2026-08-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpackage',
            name='code',
            field=models.CharField(blank=True, max_length=30, verbose_name='Code'),
        ),
    ]
