# Generated by Django 6.0.7 on 2026-08-19

from django.db import migrations, models


def initialize_work_package_dates(apps, schema_editor):
    """
    Initialise les dates de référence des lots existants
    à partir de leurs dates courantes historiques.
    """

    WorkPackage = apps.get_model(
        "work",
        "WorkPackage",
    )

    for work_package in WorkPackage.objects.all():
        work_package.initial_start_date = (
            work_package.start_date
        )
        work_package.initial_end_date = (
            work_package.end_date
        )

        work_package.save(
            update_fields=[
                "initial_start_date",
                "initial_end_date",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        (
            "work",
            "0002_alter_workpackage_code",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="workpackage",
            name="initial_end_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fin initiale",
            ),
        ),
        migrations.AddField(
            model_name="workpackage",
            name="initial_start_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Début initial",
            ),
        ),
        migrations.RunPython(
            initialize_work_package_dates,
            migrations.RunPython.noop,
        ),
    ]